### ISSUE TITLE
 The interface not defined!

### ISSUE THREAD

**Issue by SilverBiscuit** [open-cmdb/cmdb#2]
在测试过程中经常出现这样提示  The interface not defined!

api接口调用也会经常提示返回 {"detail": "The interface not defined!"}

**Comment by tangmingming** [comment]
不好意思  刚看到  请问是用什么客户端调用的？

**Comment by SilverBiscuit** [comment]
web添加数据也会有这样

**Comment by tangmingming** [comment]
后面我也遇到了  原因是我用的非官方方法实现的动态路由   不知道为什么偶尔路由会失效   你每次添加表后重启一下cmdb主程序容器应该就好了

**Comment by open-cmdb** [comment]
后面找到原因了  在Linux上热加载的路由偶尔会失效   新增表后重启一下服务器即可解决  新版已在新建表后给出重启服务端提示
